### ISSUE TITLE
CI導入

### ISSUE THREAD

**Issue by taka292** [taka292/minire#259]
### 概要

CI（継続的インテグレーション）を導入する。
GitHub Actions を使用し、プルリク作成や push 時に自動で RSpec（すでにローカル実装済）および RuboCop のチェックを実行し、品質と開発効率を向上させる。
※[参考サイト](https://qiita.com/JZ8xNeXY/items/fef7efb5eb9495b62faf)

---

### ✅ 実装内容

- [x]  `.github/workflows/test.yml` を新規作成し、以下2ジョブを構築
    - RSpec の自動実行（Capybara + remote_chrome には後続で対応）
    - RuboCop による静的解析

```yaml
yaml
コピーする編集する
# .github/workflows/test.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.6' # MiniReの使用バージョンに合わせる
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpq-dev
          bundle install

      - name: Set up database
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Rubocop
        run: bundle exec rubocop

```
